### ISSUE TITLE
Build problems with current `main` branch

### ISSUE THREAD

**Issue by tkiapril** [planetarium/pn-chrono#18]
The current `main` branch won't build, for the reasons:

1. `node-polyfill-webpack-plugin` package is listed in dependencies, but `npm i` won't install it.
2. When running `npx grunt run-all`, the following error is raised:

```
/Users/tki/RiderProjects/pn-chrono/node_modules/webpack/lib/Dependency.js:339
    		throw new Error(
    		^
    
    Error: module property was removed from Dependency (use compilation.moduleGraph.updateModule(dependency, module) instead)
        at ProvidedDependency.set (/Users/tki/RiderProjects/pn-chrono/node_modules/webpack/lib/Dependency.js:339:9)
        at iterationDependencies (/Users/tki/RiderProjects/pn-chrono/background/node_modules/webpack/lib/Compilation.js:940:21)
        at /Users/tki/RiderProjects/pn-chrono/background/node_modules/webpack/lib/Compilation.js:950:8
        at /Users/tki/RiderProjects/pn-chrono/background/node_modules/webpack/lib/NormalModuleFactory.js:409:6
        at /Users/tki/RiderProjects/pn-chrono/background/node_modules/webpack/lib/NormalModuleFactory.js:155:13
        at eval (eval at create (/Users/tki/RiderProjects/pn-chrono/background/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
        at /Users/tki/RiderProjects/pn-chrono/background/node_modules/case-sensitive-paths-webpack-plugin/index.js:178:9
        at /Users/tki/RiderProjects/pn-chrono/background/node_modules/case-sensitive-paths-webpack-plugin/index.js:125:7
        at /Users/tki/RiderProjects/pn-chrono/background/node_modules/case-sensitive-paths-webpack-plugin/index.js:125:7
        at /Users/tki/RiderProjects/pn-chrono/background/node_modules/case-sensitive-paths-webpack-plugin/index.js:125:7
        at /Users/tki/RiderProjects/pn-chrono/background/node_modules/case-sensitive-paths-webpack-plugin/index.js:125:7
        at /Users/tki/RiderProjects/pn-chrono/background/node_modules/case-sensitive-paths-webpack-plugin/index.js:125:7
        at /Users/tki/RiderProjects/pn-chrono/background/node_modules/case-sensitive-paths-webpack-plugin/index.js:125:7
        at /Users/tki/RiderProjects/pn-chrono/background/node_modules/case-sensitive-paths-webpack-plugin/index.js:125:7
        at CaseSensitivePathsPlugin.fileExistsWithCase (/Users/tki/RiderProjects/pn-chrono/background/node_modules/case-sensitive-paths-webpack-plugin/index.js:95:5)
        at /Users/tki/RiderProjects/pn-chrono/background/node_modules/case-sensitive-paths-webpack-plugin/index.js:118:10
```

On the first look, it seems like the error is caused by the mismatch of dependency versions, where other dependencies has been updated, but `webpack` hasn't. The last working commit is e1940793a610d6c9b0198e4c22aae1d7e22ef89f.

**Comment by Akamig** [comment]
It looks like your local development environment issue. I was able to run `npx grunt run-all` successfully after following README.
I executed
```
git clone <insert pn-chrono link here>
cd pn-chrono
npm install
npm --prefix background install
npm --prefix popup install
npx grunt run-all
```

My development environment is as following
```
❯ node -v
v16.15.1
❯ npm -v
8.11.0
❯ nvm -v
0.39.2
❯ uname -a
Linux Akamig 6.0.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:49 +0000 x86_64 GNU/Linux
```
Can I get more info about yours?

**Comment by tkiapril** [comment]
Apparently there was a problem with my local environment. 😢 Closing as invalid.
